<a href="https://colab.research.google.com/github/AkshatxAkki/Loan-Prediction/blob/main/Loan_Approval_Pred_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#pandas is mainly use for reading data
import pandas as pd

In [48]:
#reading data set with panda
# You can download dataset from = https://drive.google.com/file/d/15gEtHFxPtkUeGqqDkYzYmr5rDfZVLux1/view?usp=drive_link
data = pd.read_csv('loan_approval_dataset.csv')

In [3]:
#droping irrelevant column
data.drop(columns = ['loan_id'], inplace=True)

In [4]:
#Checking columns name after dropping the loan_id
data.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [5]:
#removing irrelevant spaces from column names
data.columns = data.columns.str.strip()

In [6]:
#checking if spaces get remove
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [7]:
#checking data
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [8]:
#checking columns name to make same type column as one and remove it
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [9]:
#making new column asset for all the assest type columns
data['Assets'] = data.residential_assets_value + data.commercial_assets_value+data.luxury_assets_value + data.bank_asset_value

In [10]:
#dropping all the asset type columns
data.drop(columns = ['residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value'], inplace = True)

In [11]:
#chcking if columns get remove and asset column get added
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,Graduate,No,9600000,29900000,12,778,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,Rejected,7400000
4265,0,Not Graduate,Yes,3300000,11300000,20,559,Approved,20000000
4266,2,Not Graduate,No,6500000,23900000,18,457,Rejected,39000000
4267,1,Not Graduate,No,4100000,12800000,8,780,Approved,28800000
4268,1,Graduate,No,9200000,29700000,10,607,Approved,77300000

In [12]:
#checking if there is any null value in the data
data.isnull().sum()

no_of_dependents    0
education           0
self_employed       0
income_annum        0
loan_amount         0
loan_term           0
cibil_score         0
loan_status         0
Assets              0
dtype: int64

In [13]:
#checking data after checking null values
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,Graduate,No,9600000,29900000,12,778,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,Rejected,7400000
4265,0,Not Graduate,Yes,3300000,11300000,20,559,Approved,20000000
4266,2,Not Graduate,No,6500000,23900000,18,457,Rejected,39000000
4267,1,Not Graduate,No,4100000,12800000,8,780,Approved,28800000
4268,1,Graduate,No,9200000,29700000,10,607,Approved,77300000

In [14]:
#checking all the unique value in education column (unqiue is used to print/count all repeated and non repeated value once only)
data.education.unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [15]:
#making function to remove the irrelevant spaces from data
def clean_data(st):
    st = st.strip()
    return st

In [16]:
#checking if funcation working properly
clean_data(' Graduate')

'Graduate'

In [17]:
#removing irrelevant spaces from education column by giving it to function clean_data
data.education = data.education.apply(clean_data)

In [18]:
#checking all the unique value in education column after removing spaces
data.education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [19]:
#replacing Graduate to 1 and Not Graduate to 0
data['education'] = data['education'].replace(['Graduate', 'Not Graduate'],[1,0])

In [20]:
#checking data after replacing
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,No,9600000,29900000,12,778,Approved,50700000
1,0,0,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,1,No,9100000,29700000,20,506,Rejected,57700000
3,3,1,No,8200000,30700000,8,467,Rejected,52700000
4,5,0,Yes,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,Yes,1000000,2300000,12,317,Rejected,7400000
4265,0,0,Yes,3300000,11300000,20,559,Approved,20000000
4266,2,0,No,6500000,23900000,18,457,Rejected,39000000
4267,1,0,No,4100000,12800000,8,780,Approved,28800000
4268,1,1,No,9200000,29700000,10,607,Approved,77300000

In [21]:
#checking all the unique value in self_employed column
data.self_employed.unique()

array([' No', ' Yes'], dtype=object)

In [22]:
#removing irrelevant spaces from self_employed column by giving it to function clean_data
data.self_employed = data.self_employed.apply(clean_data)

In [23]:
#checking all the unique value in self_employed column after removing spaces
data.self_employed.unique()

array(['No', 'Yes'], dtype=object)

In [24]:
#replacing No to 0 and Yes to 1
data.self_employed = data.self_employed.replace(['No', 'Yes'],[0,1])

In [25]:
#checking data after replacing
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,Approved,50700000
1,0,0,1,4100000,12200000,8,417,Rejected,17000000
2,3,1,0,9100000,29700000,20,506,Rejected,57700000
3,3,1,0,8200000,30700000,8,467,Rejected,52700000
4,5,0,1,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,Rejected,7400000
4265,0,0,1,3300000,11300000,20,559,Approved,20000000
4266,2,0,0,6500000,23900000,18,457,Rejected,39000000
4267,1,0,0,4100000,12800000,8,780,Approved,28800000
4268,1,1,0,9200000,29700000,10,607,Approved,77300000

In [26]:
#checking all the unique value in loan_status column
data.loan_status.unique()

array([' Approved', ' Rejected'], dtype=object)

In [27]:
#removing irrelevant spaces from loan_status column by giving it to function clean_data
data.loan_status = data.loan_status.apply(clean_data)

In [28]:
#checking all the unique value in loan_status column after removing spaces
data.loan_status.unique()

array(['Approved', 'Rejected'], dtype=object)

In [29]:
##replacing Approved to 1 and No to 0
data.loan_status = data.loan_status.replace(['Approved', 'Rejected'],[1,0])

In [30]:
#checking data after replacing
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,1,50700000
1,0,0,1,4100000,12200000,8,417,0,17000000
2,3,1,0,9100000,29700000,20,506,0,57700000
3,3,1,0,8200000,30700000,8,467,0,52700000
4,5,0,1,9800000,24200000,20,382,0,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,0,7400000
4265,0,0,1,3300000,11300000,20,559,1,20000000
4266,2,0,0,6500000,23900000,18,457,0,39000000
4267,1,0,0,4100000,12800000,8,780,1,28800000
4268,1,1,0,9200000,29700000,10,607,1,77300000

In [31]:
#importing train_test_split method
from sklearn.model_selection import train_test_split

In [32]:
#dividing data into 2 part input data [all the colums excepts loan_status] and output data [loan_status]
input_data = data.drop(columns=['loan_status'])
output_data = data['loan_status']

In [33]:
#checking input data
input_data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,Assets
0,2,1,0,9600000,29900000,12,778,50700000
1,0,0,1,4100000,12200000,8,417,17000000
2,3,1,0,9100000,29700000,20,506,57700000
3,3,1,0,8200000,30700000,8,467,52700000
4,5,0,1,9800000,24200000,20,382,55000000
...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,7400000
4265,0,0,1,3300000,11300000,20,559,20000000
4266,2,0,0,6500000,23900000,18,457,39000000
4267,1,0,0,4100000,12800000,8,780,28800000
4268,1,1,0,9200000,29700000,10,607,77300000

In [34]:
#checking output data
output_data

0       1
1       0
2       0
3       0
4       0
       ..
4264    0
4265    1
4266    0
4267    1
4268    1
Name: loan_status, Length: 4269, dtype: int64

In [35]:
#dividing into train and test part (train is used for training the model and test is use for check whether it can predict right or wrong)
#taking 4 variables because train_test_split return 4 outputs
#train_input,test_input,train_output,test_output = train_test_split(input data, output data, train_size = 0.2{which means 20% data is in test and 80% in train}, random_state = 1(this is use because with this every time program will take same data as input data and same as output data for both train and test))

x_train,x_test,y_train,y_test = train_test_split(input_data,output_data, test_size=0.2, random_state=1)

In [36]:
#checking the size of all the 4 variables
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3415, 8), (854, 8), (3415,), (854,))

In [37]:
#calling standardscaler for standardization (it is important to standardize data because it will lead to less retundancy, differnce between column values reduces(1,2400000,3), less error )
from sklearn.preprocessing import StandardScaler

In [38]:
#making instance of StandardScaler class
scaler = StandardScaler()

In [39]:
#standardizing input data for train
x_train_scaled = scaler.fit_transform(x_train)

In [40]:
#standardizing input data for test
x_test_scaled = scaler.transform(x_test)

#Output data is in 0 and 1 only so we don't need to standardize it

In [41]:
#importing model
from sklearn.linear_model import LogisticRegression

In [42]:
#making instance of class logiticRegression
model = LogisticRegression()

In [43]:
#fiting input_train and output_train on model or making model learn from input_train and output_train
model.fit(x_train_scaled, y_train)

LogisticRegression()

In [44]:
#checking its accuracy with input_test and output_test
model.score(x_test_scaled, y_test)

0.9215456674473068

In [45]:
#storing input data into variable
pred_data = pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents','education','self_employed','income_annum','loan_amount','loan_term','cibil_score','Assets'])

In [46]:
#standardizing input data
pred_data = scaler.transform(pred_data)

In [47]:
#prediciting wether loan approved or rejected
result = model.predict(pred_data)
if result==1:
    print('Approved')
else:
    print('Rejected')

Approved